<?php
// Grab the HEX color value from theme options
$caveat_accent = get_theme_mod( 'caveat_accentcolor', '#19a9e5' );
$caveat_headbg = get_theme_mod( 'caveat_headerbg', '#5c5c5c' );

/*-----------------------------------------------------------------
These are dynamic accent color values generated by theme options
-----------------------------------------------------------------*/

	$caveat_dynamic_accent = 'a {
			color: '.esc_html( $caveat_accent ).';
			}
			
		a:hover {
			border: '.esc_html( $caveat_accent ).';
			}
			
		::selection { 
			background: '.esc_html( $caveat_accent ).';
			}

		a.btn,
		input[type="submit"],
		button.btn,
		.more-link {
			background-color: '.esc_html( $caveat_accent ).';
			}

		#header {
			background-color: '.esc_html( $caveat_headbg ).';
			}
			
		#header .logo a {
			border-color: '.esc_html( $caveat_accent ).'
			}
				
		#header .logo a::after {
			color: '.esc_html( $caveat_accent ).'
			}

		#header #nav li.current_page_item a, 
		#header #nav li.current-menu-parent a,
		#header #nav li.current_page_parent a {
			color: '.esc_html( $caveat_accent ).'
			}

		#header #nav ul a:hover,
		#header #nav ul ul a:hover,
		#header #nav li a:hover {
			color: '. esc_html( $caveat_accent ).'!important;
			}

		#header #nav ul li.current-menu-item a {
			color: '.esc_html( $caveat_accent ).'!important;
			}

		.slicknav_nav .slicknav_arrow {
			color: '.esc_html( $caveat_accent ).'!important;
			}

		body.home #columns i {
			color: '.esc_html( $caveat_accent ).';
			}
			
		#portfolio .post a .overlay {
			background: '.esc_html( $caveat_accent ).';
			}

		#portfolio .post a:hover .overlay {
			background: '.esc_html( $caveat_accent ).';
			}

		#portfolio h2 a {
			color: '.esc_html( $caveat_accent ).';
			}

		#portfolio .flexslider-home .flex-control-paging li a.flex-active {
			background: '.esc_html( $caveat_accent ).';
			}
				
		#blog .blog-hr-heading h1 b, 
		#testimony .client-hr-heading h1 b, 
		#columns .column-hr-heading h1 b,
		#testimony #testimony-client-info strong {
			color: '.esc_html( $caveat_accent ).';
			}	
				
		#blog .blog-heading h2 a,
		#blog .post i {
			color: '.esc_html( $caveat_accent ).';
			}

		#blog .heading h1 b,
		#portfolio .heading h1 b,
		#columns .heading h1 b {
			color: '.esc_html( $caveat_accent ).';
			}

		#blog .post h2 a:hover {
			color: '.esc_html( $caveat_accent ).';
			}

		#blog .post .entry-comments a,
		#blog .post .entry-meta a {
			color:'. esc_html( $caveat_accent ).';
			}

		#content article .entry-header h2.entry-title a:hover {
			color: '.esc_html( $caveat_accent ).';
			}

		#content article .entry-content blockquote {
			border-left-color: '.esc_html( $caveat_accent ).';
			}

		#content article.format-quote .entry-title a:hover blockquote p {
			color: '.esc_html( $caveat_accent ).';
			}

		#content article.format-link .entry-image p a {
			background: '.esc_html( $caveat_accent ).';
			}
			
		#content article .entry-meta .entry-time, 
		#content article .entry-meta span a	{
			color: '.esc_html( $caveat_accent ).';
			}
			
		#content .author-bio .author-name span a {
			color: '.esc_html( $caveat_accent ).';
			}

		#content article.format-link header i {
			color: '.esc_html( $caveat_accent ).';
			}

		.mighty_project_widget .post a .overlay {
			background: '.esc_html( $caveat_accent ).';
			}

		.mighty_project_widget .post a:hover .overlay {
			background: '.esc_html( $caveat_accent ).';
			}

		.mighty_social_widget a:hover {
			background: '.esc_html( $caveat_accent ).';
			}
			
		.search-form .search-submit {
			background-color: '.esc_html( $caveat_accent ).';
			}	

		.mejs-time-current {
			background: '.esc_html( $caveat_accent ).'!important;
			}

		.mejs-controls .mejs-horizontal-volume-slider .mejs-horizontal-volume-current {
			background: '.esc_html( $caveat_accent ).'!important;
			}

		.flex-direction-nav a:hover {
			background-color: '. esc_html( $caveat_accent ).';
			}
			
		body.single .entry-meta time, 
		body.single .entry-meta span a {
			color: '.esc_html( $caveat_accent ).';
			}

		#content .author-bio .author-name a,
		#content #comments .comment-author cite {
			color: '.esc_html( $caveat_accent ).';
			}

		body.page-template-template-portfolio-sortable-php .portfolio-filter li a.active,
		body.page-template-template-portfolio-sortable-php .portfolio-filter li a:hover {
			color: '.esc_html( $caveat_accent ).';
			}

		body.page-template-template-portfolio-php .item a:hover .overlay,
		body.page-template-template-portfolio-sortable-php .item a:hover .overlay,
		body.single-portfolio #portfolio .item a:hover .overlay {
			background: '.esc_html( $caveat_accent ).';
			}
			
		body.page-template-template-portfolio-php .item a .overlay {
			background: '.esc_html( $caveat_accent ).';
			}

		body.page-template-template-portfolio-php .item a:hover .overlay,
		body.single-portfolio #portfolio .item a:hover .overlay {
			background: '.esc_html( $caveat_accent ).';
			}
			
		body.page-template-template-portfolio-php #content h2.entry-title a {
			color: '.esc_html( $caveat_accent ).';
			}

		#footer #menu-text a:hover,
		#footer .copyright a,
		#footer .social-media i {
			color: '.esc_html( $caveat_accent ).';
			}

		#footer #nav ul a:hover, 
		#footer #nav ul ul a:hover,
		#footer #nav li a:hover {
			color: '.esc_html( $caveat_accent ).'!important;
			}

		#footer li a {
			border-color: '.esc_html( $caveat_accent ).';
			}
			
		#enews form input[type="submit"] {
			background-color: '.esc_html( $caveat_accent ).';
			}
			
		.widget_categories li a { 
			color: '.esc_html( $caveat_accent ).';
			}

		.widget_recent_entries li a:hover {
			color: '.esc_html( $caveat_accent ).';
			}';
